!
hostname r2
password zebra
enable password zebra
!
interface eth1
  ip address 10.0.10.3/24
  vrrp 20
  vrrp 20 ip 10.0.10.100
  vrrp 20 priority 100
!
interface eth2
  ip address 10.0.13.1/30
!
router ospf
  ospf router-id 10.0.13.1
  network 10.0.20.0/24 area 0
  network 10.0.13.0/30 area 0
!
